"""
Django settings for web_project_1 project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

import sys
sys.path.append('C:\\Users\\Usuario\\Documents\\coding\\data-config')
import base


from django.contrib.messages import constants as error_messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5kk*^m=u_dnzyrdwsg99e-h@#lx2124##0qrh@*pm!gzmrs&u='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # date post.
    'django.contrib.humanize',
    'home_app',
    'tinymce',
    'fontawesomefree',
    'auth_app',
    'crispy_forms',
    'captcha',
    'subscribe',
    'comments',
    'mptt',
    # Google auth apps.
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
]

APPEND_SLASH    =   False

# CUSTOMUSER REGISTRATION
AUTH_USER_MODEL = 'auth_app.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web_project_1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_project_1.wsgi.application'


# DATABASE SETTINGS
# # https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': base.ENGINE,
        'NAME': base.NAME, 
        'USER': base.USER, 
        'PASSWORD': base.PASSWORD,
        'HOST': base.HOST, 
        'PORT': base.PORT, 
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# PATH TO SAVE ALL MEDIA FILES.
MEDIA_URL = '/media/' 
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# EMAIL CONFORMATION SINGUP SETUP

EMAIL_BACKEND = base.EMAIL_BACKEND
EMAIL_HOST= base.EMAIL_HOST
EMAIL_USE_TLS = base.EMAIL_USE_TLS
EMAIL_PORT= base.EMAIL_PORT
EMAIL_FROM = base.EMAIL_FROM
EMAIL_HOST_USER = base.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = base.EMAIL_HOST_PASSWORD
PASSWORD_RESET_TIMEOUT = base.PASSWORD_RESET_TIMEOUT


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Error levels tags. imported from line 15
MESSAGE_TAGS={
    
    error_messages.DEBUG: 'debug',
    error_messages.INFO: 'info',
    error_messages.SUCCESS: 'success',
    error_messages.WARNING: 'warning',
    error_messages.ERROR: 'error',
}

CRISPY_TEMPLATE_PACK='bootstrap4'

LOGIN_REDIRECT_URL= '/'

# THIS OVERRIDE DEFAULT DJANGO AUTHENTICATION TO USE THIS
# GOOGLE AUTH BACKENDS
AUTHENTICATION_BACKENDS = ['auth_app.backends.EmailBackend',
                           'allauth.account.auth_backends.AuthenticationBackend']

#------------------
# GOOGLE AUTH CONFIG
SITE_ID = 1
SOCIALACCOUNT_LOGIN_ON_GET= True

SOCIALACCOUNT_PROVIDERS ={
    'google':{
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}
#---------------------

#DJANGO CAPTCHA
RECAPTCHA_PUBLIC_KEY = base.RECAPTCHA_PUBLIC_KEY
RECAPTCHA_PRIVATE_KEY = base.RECAPTCHA_PRIVATE_KEY
SILENCED_SYSTEM_CHECKS = base.SILENCED_SYSTEM_CHECKS


#----------------------

SECURE_SSL_REDIRECT = False

#----------------------


# TEXT EDITOR FOR POSTS

DATA_UPLOAD_MAX_MEMORY_SIZE =   5242880

TINYMCE_DEFAULT_CONFIG = {
    'custom_undo_redo_levels': 100,
    'selector': 'textarea',
    "menubar": "file edit view insert format tools table help",
    'plugins': 'link image preview codesample contextmenu table code lists fullscreen',
    'toolbar1': 'undo redo | backcolor casechange permanentpen formatpainter removeformat formatselect fontselect fontsizeselect',
    'toolbar2': 'bold italic underline blockquote | alignleft aligncenter alignright alignjustify '
               '| bullist numlist | outdent indent | table | link image | codesample | preview code | tiny_mce_wiris_formulaEditor tiny_mce_wiris_formulaEditorChemistry',
    'contextmenu': 'formats | link image',
    'block_formats': 'Paragraph=p; Header 1=h1; Header 2=h2',
    'fontsize_formats': "8pt 10pt 12pt 14pt 16pt 18pt",
    'content_style': "body { font-family: Arial; background: white; color: black; font-size: 12pt}",
    'codesample_languages': [
        {'text': 'Python', 'value': 'python'}, {'text': 'HTML/XML', 'value': 'markup'},],
    'image_class_list': [{'title': 'Fluid', 'value': 'img-fluid', 'style': {} }],
    'width': 'auto',
    "height": "600px",
}

